# Ordered neighbor definitions preserve AD* tie-breaking.
3d:
  resolution: 1
  epsilon: 2.5
  epsilon_increment: 0.2
  epsilon_decrement: 0.2
  bounds:
  - - -10
    - -10
    - -10
  - - 10
    - 10
    - 10
  neighbors:
  - direction:
    - 1
    - 0
    - 0
    cost: 1.0
  - direction:
    - 0
    - 1
    - 0
    cost: 1.0
  - direction:
    - 0
    - 0
    - 1
    cost: 1.0
  - direction:
    - -1
    - 0
    - 0
    cost: 1.0
  - direction:
    - 0
    - -1
    - 0
    cost: 1.0
  - direction:
    - 0
    - 0
    - -1
    cost: 1.0
  - direction:
    - 1
    - 1
    - 0
    cost: 1.4142135623730951
  - direction:
    - 1
    - 0
    - 1
    cost: 1.4142135623730951
  - direction:
    - 0
    - 1
    - 1
    cost: 1.4142135623730951
  - direction:
    - -1
    - -1
    - 0
    cost: 1.4142135623730951
  - direction:
    - -1
    - 0
    - -1
    cost: 1.4142135623730951
  - direction:
    - 0
    - -1
    - -1
    cost: 1.4142135623730951
  - direction:
    - 1
    - -1
    - 0
    cost: 1.4142135623730951
  - direction:
    - -1
    - 1
    - 0
    cost: 1.4142135623730951
  - direction:
    - 1
    - 0
    - -1
    cost: 1.4142135623730951
  - direction:
    - -1
    - 0
    - 1
    cost: 1.4142135623730951
  - direction:
    - 0
    - 1
    - -1
    cost: 1.4142135623730951
  - direction:
    - 0
    - -1
    - 1
    cost: 1.4142135623730951
  - direction:
    - 1
    - 1
    - 1
    cost: 1.7320508075688772
  - direction:
    - -1
    - -1
    - -1
    cost: 1.7320508075688772
  - direction:
    - 1
    - -1
    - -1
    cost: 1.7320508075688772
  - direction:
    - -1
    - 1
    - -1
    cost: 1.7320508075688772
  - direction:
    - -1
    - -1
    - 1
    cost: 1.7320508075688772
  - direction:
    - 1
    - 1
    - -1
    cost: 1.7320508075688772
  - direction:
    - 1
    - -1
    - 1
    cost: 1.7320508075688772
  - direction:
    - -1
    - 1
    - 1
    cost: 1.7320508075688772
